### ISSUE TITLE
Printing an AGN Grid object appears to break

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#749] opened 2024-10-01 13:15 UTC
Printing an AGN Grid object appears to break.

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[3], line 8
      2 grid_dir = "/Users/sw376/Dropbox/Research/data/synthesizer/grids/"
      3 grid = Grid(
      4     grid_name=disc_model, 
      5     grid_dir=grid_dir,
      6     read_lines=False)
----> 8 print(grid)

File ~/Dropbox/Research/projects/synthesizer/src/synthesizer/grid.py:635, in Grid.__str__(self)
    632 # Intialise the table formatter
    633 formatter = TableFormatter(self)
--> 635 return formatter.get_table("Grid")

File ~/Dropbox/Research/projects/synthesizer/src/synthesizer/utils/ascii_table.py:230, in TableFormatter.get_table(self, title_text)
    217 """
    218 Generate a formatted table.
    219 
   (...)
    227         The formatted table as a string.
    228 """
    229 rows = self.get_value_rows()
--> 230 rows.extend(self.get_list_rows())
    231 rows.extend(self.get_array_rows())
    232 rows.extend(self.get_dict_rows())

File ~/Dropbox/Research/projects/synthesizer/src/synthesizer/utils/ascii_table.py:208, in TableFormatter.get_list_rows(self)
    206 for attr, value in self.attributes.items():
    207     if isinstance(value, list):
--> 208         formatted_values = self.format_list(value)
    209         for i, formatted_value in enumerate(formatted_values):
    210             if i == 0:

File ~/Dropbox/Research/projects/synthesizer/src/synthesizer/utils/ascii_table.py:111, in TableFormatter.format_list(self, lst)
    109     out.append("".join(line) + "]")
    110 else:
--> 111     out[-1] += "]"
    112 return out

IndexError: list index out of range
```

**Comment by WillJRoper** [comment] 2024-10-01 13:18
How have you managed that 😂 `out` is defined with the function... do you have an empty list or something? I don't get how that can fail.

**Comment by WillJRoper** [comment] 2024-10-08 10:44
@stephenmwilkins, I can't reproduce this behaviour on `main` so I assume it's something you've introduced on a branch. I'm closing this issue since it appears to work.

**Comment by WillJRoper** [comment] 2024-10-08 10:46
Ah, no, I made it happen. The `read_lines=False` is the important part.

**Closed** 2024-10-15 07:23 UTC
Labels: bug, grid
