### ISSUE TITLE
Make it easier to use matplotlib style sheets with Synthesizer plots 

### ISSUE THREAD

**Issue by sophie-newman** [flaresimulations/synthesizer#581] opened 2024-04-12 09:33 UTC
When I try to use something like 

```
tex_fonts = {
    "font.family": "serif",
    # Use 10pt font in plots, to match 10pt font in document
    "axes.labelsize": 10,
    "font.size": 10,
    # Make the legend/label fonts a little smaller
    "legend.fontsize": 8,
    "xtick.labelsize": 8,
    "ytick.labelsize": 8
}

plt.rcParams.update(tex_fonts)
```

or use a style sheet with `plt.style.use('mystyle.mplstyle')` ,

I either get errors when making Synthesizer plots or the font doesn't change, depending on where I place this within my code.

I think a solution that makes this more user-friendly would be ideal.

**Comment by WillJRoper** [comment] 2024-04-15 21:08
Note as I said on Slack, this may be something to do with Matplotlib not something we have actively done. The plots produced by Synthesizer aren't necessarily meant to be publication ready. It may come down to needing users to make their own plots if they want fine control over the style.

**Comment by WillJRoper** [comment] 2024-04-15 21:21
I've now double checked and nowhere internally is the font or style set so there's nothing to override your style file or `rcParams` internally. 

Can you create a MRE? Can you check your style file applies as you expect outside of Synthesizer? 

If it's the font that is specifically not changing it could be you are requesting an unavailable font. Run:
```
import matplotlib.font_manager as font_manager

# List available fonts
fonts = [f.name for f in font_manager.fontManager.ttflist]
print("Available fonts:", fonts)
```
to check.

**Comment by sophie-newman** [comment] 2024-04-16 09:03
here's my minimal example, and I've checked the font is available - you'll just need to change the grid you're looking at

```
import matplotlib.pyplot as plt
from synthesizer.grid import Grid

plt.rcParams['figure.dpi'] = 200

plt.rcParams["font.family"] = "Tlwg Typewriter"

#Load the grid
grid_dir = '/home/sophienewman/data/synthesizer_data/grids'

grid_name = 'maraston13_pagb_exotic_kroupa_cloudy-c23.01-sps-pagb'
grid = Grid(grid_name, grid_dir=grid_dir, read_lines=True)

fig, ax = grid.plot_specific_ionising_lum(ion='HI', vmin=14.6, vmax=41.3)

# It seems the fonts for the numbers change, but not the actual labels
```

**Comment by WillJRoper** [comment] 2024-04-16 09:13
Ok, this isn't a Synthesizer issue but instead something with Matplotlib. I reproduced this on the command line. To make the plot I posted in random on Slack I had to pass the font explicitly to the label. 

It could be related to this: https://stackoverflow.com/questions/68517139/matplotlib-appears-to-not-use-rcparams-when-plotting-particularly-for-text-e-g

I'm closing this issue since it's not Synthesizer and I'm not convinced we should fix it. The labels can be modified after the fact using the returned ax object if you want but Synthesizer's outputs aren't designed to be used for publication, they are quick checks.

**Closed by WillJRoper** 2024-04-16 09:13 UTC
